feat: activated the links of the packages page
apu52/Travel_Website pull request #1335
Opened 2024-08-06 17:46 UTC by ayush-848

# Title and Issue number 

Title : activated the links of the packages page

Issue No. : #1318

Code Stack : html, css

Close #1318

# Description
FIXED THE LINKS
FIXED THE MEMBERSHIP SECTION
ADDED LINKS TO THE HOTEL PHOTOS

# Video/Screenshots (mandatory)
![image](https://github.com/user-attachments/assets/3c73ca45-4ed5-431a-8a02-0f218a5b05d0)

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [x] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

2024-08-07 20:39 UTC, apu52 requested changes
![image](https://github.com/user-attachments/assets/c81ee942-b7f8-4f3f-9dc4-c9cb17af239a)

the purchase button is not working . Please link this button with the booking page

2024-08-07 21:04 UTC, ayush-848 commented
@apu52 check it now

2024-08-08 16:09 UTC, apu52 approved these changes

2024-08-08 16:10 UTC, merged

2024-08-08 16:10 UTC, apu52 commented
@ayush-848 great work