footer UI fixed
apu52/Travel_Website pull request #564
Opened 2024-05-24 08:12 UTC by kairveeehh

# Title and Issue number 
#408 footer's improvement
Title : Improved the footer

Issue No. : 408

Code Stack : html and css

Close #408 
1. fixed the problem of text line's changing on hovering the text 
2. added social icons for better UI 
3. improved the generalisation of colors
4. added hover effects 
![Screenshot 2024-05-15 143748](https://github.com/apu52/Travel_Website/assets/145572028/0faeca06-ad80-4357-ac39-2ae167600677)
![Screenshot 2024-05-15 143742](https://github.com/apu52/Travel_Website/assets/145572028/610341c4-3bc9-43e2-b2a3-12d75146ac5d)
![Screenshot 2024-05-15 143734](https://github.com/apu52/Travel_Website/assets/145572028/541ae908-7e76-487b-b820-91f1386b6388)# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***
GSSOC'24

2024-05-24 08:14 UTC, kairveeehh commented
@apu52  I have recreate a new PR with no conflicts with the main branch and all checks have been passes as well , please make sure to merge it so that no other conflicts arise further 
thankyou , 
kairvee

2024-05-25 11:52 UTC, kairveeehh commented
@apu52 please inform

2024-05-25 12:05 UTC, kairveeehh commented
> @apu52 please inform and merge

2024-05-25 12:10 UTC, apu52 commented
@kairveeehh please wait  for sometime .I am reviewing other PRs in this repo .I will also review this PR very soon .Just Don't worry . 

& sorry as you have faced merge conflict problems in the previous PR due to late review of mine.

2024-05-25 13:51 UTC, kairveeehh commented
> @kairveeehh please wait  for sometime .I am currently reviewing other PRs in this repo .I will also review this PR very soon .Just Don't worry . 
> 
> & sorry as you have faced merge conflict problems in the previous PR due to late review of mine.

Sure and waiting

2024-05-25 14:40 UTC, apu52 requested changes
![image](https://github.com/apu52/Travel_Website/assets/114172928/47e3bffc-08f5-48d1-9081-24254ae40d28)

in dark theme the other Social icons are not visible , I also want to suggest to change the hover color of social icons according to their custom color (e.g insta--red)

2024-05-25 14:40 UTC, apu52 commented on styles.css
> +
@kairveeehh there is a problem 

![image](https://github.com/apu52/Travel_Website/assets/114172928/c3e93bd5-ce1f-4665-aab5-f914f92b1851)

The Headings are not visible

2024-05-25 16:03 UTC, kairveeehh commented
> ![image](https://private-user-images.githubusercontent.com/114172928/333807478-47e3bffc-08f5-48d1-9081-24254ae40d28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NTMyMjEsIm5iZiI6MTcxNjY1MjkyMSwicGF0aCI6Ii8xMTQxNzI5MjgvMzMzODA3NDc4LTQ3ZTNiZmZjLTA4ZjUtNDhkMS05MDgxLTI0MjU0YWU0MGQyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxNjAyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjBiZGVlNTQyM2NhNjljZjhhOTRjOTNmYTg2OTgzNGMzMzliYzI4NDA5OTJiZjhlZGYyZjdhNmEwNTRmNzcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._leIP5lxY9lbACIi3L2TdgE4b6wmB39_kz7xOBOJVbs)
> 
> in dark theme the other Social icons are not visible , I also want to suggest to change the hover color of social icons according to their custom color (e.g insta--red)

okay suree , I will look into all these chnages by tonight or morning @apu52

2024-05-30 06:17 UTC, kairveeehh commented
@apu52  I am adding tooltips as well , please tell which all social icons you want with the ids and what specific color?
![Screenshot 2024-05-30 114625](https://github.com/apu52/Travel_Website/assets/145572028/01c19873-bd24-41c2-abfb-8f6e9b3f6cb6)

2024-06-01 06:52 UTC, apu52 commented
> Author

you can add Insta , facebook , twitter , linkedin as social icons

2024-06-07 11:59 UTC, apu52 commented
I am closing this PR as this issue has already been exhausted.

2024-06-07 11:59 UTC, closed without merging