Remove margin from paragraphs under about us section
apu52/Travel_Website pull request #602
Opened 2024-05-25 15:48 UTC by rudravashishtha

Title : Bug in About Us Section

Issue No. : #601 

Code Stack : HTML

Close #601 

I have removed the extra left margin from all the paragraphs under about us section.

Before:
![image](https://github.com/apu52/Travel_Website/assets/91290891/d1f92763-2e8b-46e2-b1e8-f7199a541dc0)

![image](https://github.com/apu52/Travel_Website/assets/91290891/3c885576-526d-4ae8-ac7b-a0f6a00f0b07)

After:
![image](https://github.com/apu52/Travel_Website/assets/91290891/5f46fe9e-8bc0-412e-a3d3-01e6235374cd)

![image](https://github.com/apu52/Travel_Website/assets/91290891/f99e1339-988d-49fa-b901-8693140055f1)

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have gone through the  `contributing.md` file before contributing

I am contributing under GSSOC'24.

2024-05-25 16:03 UTC, apu52 requested changes
@rudravashishtha change the left alignment into  center & break that PARA in a single para which will look well according to the website

2024-05-25 16:21 UTC, apu52 commented
> > @rudravashishtha change the left alignment into center & break that PARA in a single para which will look well according to the website
> 
> ![image](https://private-user-images.githubusercontent.com/91290891/333816796-d6ea8f38-d4b8-475a-aa15-2d20517e6d7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NTQyNzQsIm5iZiI6MTcxNjY1Mzk3NCwicGF0aCI6Ii85MTI5MDg5MS8zMzM4MTY3OTYtZDZlYThmMzgtZDRiOC00NzVhLWFhMTUtMmQyMDUxN2U2ZDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDE2MTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1OGM4MmZjMDZmM2E3NTQ0OTRhMDc0ZTkwMTM3YzcwMTNmODI4Y2Q3ZWMzZjg4NmFjM2U3ODFiZDViZTg0NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.80BIfptd4eREmlxwiPt13Pu3Sa2wkGmrYXMhVSb8cSo)
> 
> Do you want it like this?

like it just make the paragraph more spread in horizontal way

2024-05-25 16:28 UTC, rudravashishtha commented
> > > @rudravashishtha change the left alignment into center & break that PARA in a single para which will look well according to the website
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/91290891/333816796-d6ea8f38-d4b8-475a-aa15-2d20517e6d7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NTQyNzQsIm5iZiI6MTcxNjY1Mzk3NCwicGF0aCI6Ii85MTI5MDg5MS8zMzM4MTY3OTYtZDZlYThmMzgtZDRiOC00NzVhLWFhMTUtMmQyMDUxN2U2ZDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDE2MTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1OGM4MmZjMDZmM2E3NTQ0OTRhMDc0ZTkwMTM3YzcwMTNmODI4Y2Q3ZWMzZjg4NmFjM2U3ODFiZDViZTg0NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.80BIfptd4eREmlxwiPt13Pu3Sa2wkGmrYXMhVSb8cSo)
> > Do you want it like this?
> 
> like it just make the paragraph more spread in horizontal way

So you want the whole about us div to be centered on the screen?

2024-05-26 05:58 UTC, Vikashchou-dhary commented
@apu52 my previous changes for issue #599 has solved this issue
![travel changes1](https://github.com/apu52/Travel_Website/assets/158028747/25b0199f-ad69-46e1-8952-5f907ffbcc7c)

2024-06-07 11:58 UTC, closed without merging