Resolved Dark Mode Persistance Issue After refreshing
apu52/Travel_Website pull request #797
Opened 2024-06-07 16:38 UTC by aslams2020

Hi @apu52,
Title : Dark mode gets turned off on refeshing a page
Issue Close #732 

## Description
I have resolved the issue to persist the dark mode preference across page refreshes using localStorage.
The changes ensure that the user's selected mode (dark or light) is maintained even after the page is refreshed.
Please take a look and review it.

## Changes made :
- To make the dark mode preference persist across page refreshes, used "localStorage" to save the user's preference.
- Then Saved the theme preference in localStorage whenever the theme is toggled.
- and then Checked the saved theme preference when the page loads and apply it accordingly.

# Video/Screenshots (mandatory)

https://github.com/apu52/Travel_Website/assets/131389695/8a466c0e-1ac4-48fa-8408-a028b67f4988

# Type of PR

- [x] Bug fix
- [x] Feature enhancement

# Checklist:

- [x] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have gone through the  `contributing.md` file before contributing

##Are you contributing under any Open-source programme?
GSSOC'24

Could you please review and also give required labels?

2024-06-07 17:26 UTC, aslams2020 commented
@apu52 i resolved the issue. It is working fine now. Please take a look

2024-06-09 05:29 UTC, aslams2020 commented
Hi @apu52,
Could you Please take a look. also add required labels.

2024-06-14 05:24 UTC, aslams2020 commented
@apu52

2024-06-25 16:15 UTC, apu52 requested changes
@aslams2020 
![image](https://github.com/apu52/Travel_Website/assets/114172928/49b083da-40a3-48f2-9362-36013dd498a0)

The theme button is not working in your PR . please try to check its functionality .

2024-06-25 16:28 UTC, aslams2020 commented
@apu52, I just checked it and it's working fine.

Please take a look - 

https://github.com/apu52/Travel_Website/assets/131389695/3e11ad2b-4c0b-4de2-a2ef-fe67ccf3a076

2024-06-26 13:44 UTC, apu52 approved these changes

2024-06-26 13:44 UTC, apu52 commented
> @apu52, I just checked it and it's working fine.
> 
> Please take a look -
> 
>  TravelWebsite.Issue.mp4

yes .now its working fine

2024-06-26 13:44 UTC, merged