Replaced previous website logo
apu52/Travel_Website pull request #951
Opened 2024-06-29 22:03 UTC by Gultreen

Title : Replacing name with logo in the navbar

Issue No. : #844

Code Stack : HTML , CSS

Close #844

# Description

# Video/Screenshots (mandatory)

![hhhhh](https://github.com/apu52/Travel_Website/assets/145576858/9e91b0ef-560f-47c6-a1a0-69ae0ee282fd)

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have performed a self-review of my code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have gone through the  `contributing.md` file before contributing

# Additional context:

##Are you contributing under any Open-source programme?

- [X] I am contributing under `GSSOC'24`
- [ ] I am contributing under `VSOC'24`

2024-07-03 16:45 UTC, apu52 requested changes

2024-07-03 16:45 UTC, apu52 commented on styles.css
![image](https://github.com/apu52/Travel_Website/assets/114172928/dd5b4cde-ed49-4e61-aa8b-574df24228af)

![image](https://github.com/apu52/Travel_Website/assets/114172928/c93b4adc-c2ea-4ed0-aac0-e01f943c7a21)

I think there are literally some serious bugs I have found due to this width change .please try to resolve this so that I can review & merge your pR

2024-07-21 11:53 UTC, Gultreen commented on styles.css
I have resolved the conflict.kindly look at the PR.

2024-07-22 13:21 UTC, apu52 approved these changes
@Gultreen good work

2024-07-22 13:21 UTC, merged